version: 2.1
jobs:
  check-index-json-files:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Check files listed in index.json exist in repository
          command: |
            set -e
            if ! command -v jq >/dev/null 2>&1; then
              sudo apt-get update && sudo apt-get install -y jq
            fi
            files=$(jq -r '.[]' index.json)
            missing=0
            for file in $files; do
              if [ ! -e "$file" ]; then
                echo "Missing: $file"
                missing=1
              fi
            done
            if [ "$missing" -eq 1 ]; then
              echo "Some files listed in index.json are missing in the repository." >&2
              exit 1
            else
              echo "All files listed in index.json exist in the repository."
            fi
workflows:
  check-index-json-workflow:
    jobs:
      - check-index-json-files
