version: 2.1
jobs:
  check-template-files:
    docker:
      - image: cimg/node:18.20.2
    steps:
      - checkout
      - run:
          name: Checkout PR commit if CIRCLE_PR_NUMBER exists
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "Checking out PR #$CIRCLE_PR_NUMBER commit..."
              git fetch origin pull/$CIRCLE_PR_NUMBER/head:pr-$CIRCLE_PR_NUMBER
              git checkout pr-$CIRCLE_PR_NUMBER
            else
              echo "No PR number, using default checkout."
            fi
      - run:
          name: 检查 template_list 里的 file_name 是否存在（排除 "null"）
          command: |
            node -e '
              const fs = require("fs");
              const path = require("path");
              const index = JSON.parse(fs.readFileSync("index.json", "utf8"));
              let missing = [];
              for (const tpl of index.template_list) {
                if (tpl.file_name && tpl.file_name !== "null") {
                  if (!fs.existsSync(path.join(".", tpl.file_name))) {
                    missing.push(tpl.file_name);
                  }
                }
              }
              if (missing.length > 0) {
                console.error("以下模板文件缺失:");
                for (const f of missing) console.error(f);
                process.exit(1);
              } else {
                console.log("所有模板文件都存在。");
              }
            '
workflows:
  version: 2
  check-templates:
    jobs:
      - check-template-files
